on:
  push:
    branches:
    - main
    - release/*
    paths:
    - 'src/couponservice/**'
    - 'src/compose.yml'
  pull_request:
    branches:
    - main
    paths:
    - 'src/couponservice/**'
    - 'src/compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        server-id: github
        settings-path: ${{ github.workspace }}
    
    - name: Run Commands
      run: |
        echo "JAVA_HOME=${JAVA_HOME}"
        echo "MAVEN_HOME=${MAVEN_HOME}"
        echo "PATH=${PATH}"
        java -version
        mvn -version
        docker --version
        echo "PWD: ${pwd}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        # Print environment variables
        env

    - name: Start PostgreSQL
      run: docker compose -f compose.yml up -d web-db
      working-directory: src

    - name: Build with Maven
      run: mvn -B clean install
      working-directory: src/couponservice
