name: Coupon Service CI Pipeline

on:
  push:
    branches:
      - main
      - MCS-*
  pull_request:
    branches:
      - main
  paths:
    - 'src/couponservice/**'
    - 'src/compose.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'correto'
    
    - name: Start PostgreSQL
      run: docker-compose -f compose.yml up -d web-db
      working-directory: src

    - name: Build with Maven
      run: mvn -B clean install -Dspring.profiles.active=dev
      working-directory: src/couponservice


